CONST TR = REQUIRE('THROUGH2');
CONST FS = REQUIRE('FS');
CONST SPLIT = REQUIRE('SPLIT');
FS.CREATEREADSTREAM('TRANSFORM1.JS')
  .PIPE(SPLIT())
  .PIPE(TR(FUNCTION(BUF, _, NEXT){
      IF(BUF.TOSTRING().LENGTH > 15){
          CONSOLE.LOG(BUF.TOSTRING().LENGTH);
          THIS.PUSH(BUF.TOSTRING().TOUPPERCASE());
          THIS.PUSH('\N');
  .PIPE(FS.CREATEWRITESTREAM('FILES/TRANSFORM.JS'));
